version: '2'

services:
  app:

    image: seneca-tech-task
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=3000
      - LOG_LEVEL=debug
      # The following need to match the postgres container env variables
      - DB_HOST=database
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_DATABASE=seneca
      - DB_PORT=5432
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/app/src
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seneca
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
